Add exit 1 back

diff --git a/.github/actions/extract-data-string-from-file/action.yml b/.github/actions/extract-data-string-from-file/action.yml
--- a/.github/actions/extract-data-string-from-file/action.yml
+++ b/.github/actions/extract-data-string-from-file/action.yml
@@ -19,11 +19,11 @@ runs:
       shell: bash
       run: |
         if [ -z "${{ inputs.path }}" ]; then
-          echo "::error::Path is required"
+          echo "::error::Path is required" && exit 1
         elif [ ! -e "${{ inputs.path }}" ]; then
-          echo "::error::Path does not exist"
+          echo "::error::Path does not exist" && exit 1
         elif [ -d "${{ inputs.path }}" ]; then
-          echo "::error::Path is a directory"
+          echo "::error::Path is a directory" && exit 1
         else
           DATA=$(cat "${{ inputs.path }}")
           {
